#!/bin/bash

# Update packages
sudo apt update

# Install Nginx
sudo apt install -y nginx

# Get the hostname
HOSTNAME=$(hostname)

# Configure Nginx to add custom header
sudo sed -i "s|http {|http {\n    add_header X-Served-By $HOSTNAME;|" /etc/nginx/nginx.conf

# Restart Nginx
sudo systemctl restart nginx
