#!/usr/bin/env bash
#Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
sudo apt update
sudo apt install -y nginx
HOSTNAME=$(hostname)
sudo sed -i "s|http {|http {\n    add_header X-Served-By $HOSTNAME;|" /etc/nginx/nginx.conf
sudo systemctl restart nginx
