#!/usr/bin/env bash
# Change localhost to 127.0.0.2
# Change facebook.com to 8.8.8.8

#back up the original hosts file
sudo cp /etc/hosts /etc/hosts.old

#update the hosts file with the new local host entry
sudo echo "127.0.0.2 localhost" >> /etc/hosts
sudo echo "8.8.8.8 facebook.com" >> /etc/hosts


#display the contents of the hosts file
cat /etc/hosts



